#What are ufuncs?
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object

##Why use ufuncs?
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where boolean array or condition defining where the operations should take place.

dtype defining the return type of elements.

out output array where the return value should be copied.

## What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

## Add the Elements of Two Lists
list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements

In [1]:
#we can use Python's built-in zip() method:
x = [1,2,3,4]
y = [5,6,7,8]
z=[]
for i, j in zip(x,y):
  z.append(i+j)
print(z)


[6, 8, 10, 12]


In [6]:
#we can use the add() function:
import numpy as np
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)
print(type(np.add))
print(z)

<class 'numpy.ufunc'>
[ 5  7  9 11]


###To create your own ufunc,
you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (arrays).
outputs - the number of output arrays.

In [5]:
#How To Create Your Own ufunc
def myadd(x, y):
  return x+y
myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [8]:
print(type(np.add))
print(type(np.concatenate))

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

<class 'numpy.ufunc'>
<class 'function'>
add is ufunc


##Simple Arithmetic

In [12]:
#addition
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)


print("Sum of 2 arrys is : ",newarr)

Sum of 2 arrys is :  [30 32 34 36 38 40]


In [13]:
#Subtraction
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)
print("Subtract of 2 arrys is : ",newarr)

Subtract of 2 arrys is :  [-10 -10 -10 -10 -10 -10]


In [14]:
#Multiplication
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [15]:
#Division
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [16]:
#Power
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [17]:
#Remainder
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [18]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [19]:
#Quotient and Mod
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [20]:
#Absolute Values
# negitive ho  to positive kr data hai
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


##Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

1.truncation
2.fix
3.rounding
4.floor
5. ceil

In [22]:
#Truncation
#Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [23]:
arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [24]:
#Rounding
#Round off 3.1666 to 2 decimal places:
arr = np.around(3.1666, 2)

print(arr)

3.17


In [25]:
#Floor
#The floor() function rounds off decimal to nearest lower integer.
arr = np.floor([-3.1666, 3.6667])

print(arr)


[-4.  3.]


In [26]:
#Ceil
#The ceil() function rounds off decimal to nearest upper integer.
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


##NumPy Products
To find the product of the elements in an array, use the prod() function.

In [27]:
#because 1*2*3*4 = 24
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [28]:
#because 1*2*3*4*5*6*7*8 = 40320
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [29]:
#Product Over an Axis
#If you specify axis=1, NumPy will return the product of each array.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [30]:
#Cummulative Product
#Cummulative product means taking the product partially.

#E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

#Perfom partial sum with the cumprod() function.
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)


[   5   30  210 1680]


#NumPy Differences
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [31]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


##Finding LCM in Arrays

In [32]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [33]:
arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [34]:
#Find the LCM of all values of an array where the array contains all integers from 1 to 10:
arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


##Finding GCD (Greatest Common Denominator)  /HCF

In [35]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)


3


In [36]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


#Create Sets in NumPy

In [37]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


#Finding Union

In [38]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


#Finding Intersection

In [39]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [40]:
#Finding Difference
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)


[1 2]


In [41]:
#Finding Symmetric Difference
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
