#NumPy

In [1]:
# NumPy is a Python library.

# NumPy is used for working with arrays.

# NumPy is short for "Numerical Python".
#NumPy was created in 2005 by Travis Oliphant.
# hum log dusri labguage m be array ka use kr sakta hai but numpy mai hum array k sath 50 guna jayda spped sa deal kr sakta hai

#numpy is python library but it is written in c and c++



In [2]:
#Installation of NumPy
# ydi hum juipter notebook, pycharme pr work karta hai to pip ka use krk numpy install karna hoge or online pahla sa install hota hai
#pip install numpy # IDE k liy
#import numpy  # online k liy
#import numpy as np    # bar bar numpy nhi likhna pd issliy np

In [3]:
# Here we are finding version
import numpy as np
print(np.__version__)

1.23.5


In [4]:
# create a numpy array

import numpy as np
arr = np.array([1,2,True, "kapil", 1.2, 0, 12])
print(arr) #here i am print array
print(type(arr)) #find what type of array


['1' '2' 'True' 'kapil' '1.2' '0' '12']
<class 'numpy.ndarray'>


In [5]:
arr= np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


###Dimension in Array

In [6]:
# 0-D Array
# ydi [] nhi lagta to 0 D array hota hai
d0 = np.array(12)
print(d0)
print(type(d0))
print(d0.ndim) #help of n dim we can find how many dinensions

12
<class 'numpy.ndarray'>
0


In [7]:
#1-D Arrays

d1=np.array(["ram","shyam","geeta"])
print(d1)
print(type(d1))
print(d1.ndim)

['ram' 'shyam' 'geeta']
<class 'numpy.ndarray'>
1


In [8]:
#2-D Arrays
# once we are import numpy then no need to again import
d2=np.array([[1,2,3],[4,5,6]])
print(d2)
print(type(d2))
print(d2.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [9]:
#3-D arrays
d3=np.array([[[1,2,3],["ram","shyam","geeta"],[10,12,15]]])
print(d3)
print(type(d3))
print(d3.ndim)

[[['1' '2' '3']
  ['ram' 'shyam' 'geeta']
  ['10' '12' '15']]]
<class 'numpy.ndarray'>
3


In [10]:
#Higher Dimensional Arrays
# we can change the array dimensional
dmulti = np.array([1,2,3,4,5], ndmin=5)
print(dmulti)
print("Dimension of array is", dmulti.ndim)

[[[[[1 2 3 4 5]]]]]
Dimension of array is 5


###Array Indexing

In [11]:
#in the array indexes array starts with 0
arrindex = np.array([1,2,3,5])
print(arrindex)
print(arrindex[0])
print(arrindex[0] + arrindex[1])
print(arrindex[1] + arrindex[2])

[1 2 3 5]
1
3
5


In [12]:
# access 2-D Array
#to access element form 2-D arrays we can use comma separated integers

A2D = np.array([[1,2,3,4],[5,6,7,8]])
print('2nd element in the 1st row=', A2D[0,3])

2nd element in the 1st row= 4


In [13]:
# access 3-D Array
ar3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(ar3[0,0,1])

2


In [14]:
#Negative Indexing
arrnegitive = np.array([[1,2,3,4],[5,6,7,8]])
print("aceess last element",arrnegitive[1,-1])
print("aceess last element",arrnegitive[1,-2])
print("aceess last element",arrnegitive[0,-2])
print("aceess last element",arrnegitive[:])  #we can copy complete array




aceess last element 8
aceess last element 7
aceess last element 3
aceess last element [[1 2 3 4]
 [5 6 7 8]]


###Array Slicing

In [15]:
#in python slicng means taking elements from one given index to another given index
#[start : end]
#[start :end: step]
#we don't pass start its considered 0
#we don't pass end its considered length of array in that dimension
#we don't pass step its considered 1
arrslice = np.array([1,2,3,4,5,6,7,8,9])
print(arrslice[2:6])  #1st include and second is exclude
#array index start from 0
print(arrslice[6:])  #it's mena start form 6 to end of the array
print(arrslice[:2]) #it's mean only 2 element first and second
print(arrslice[-3:-1])

# here to we are doing STEP
print('step 2 element:',arrslice[2:6:2])
print(arrslice[::2]) #return every other element from the entire array

[3 4 5 6]
[7 8 9]
[1 2]
[7 8]
step 2 element: [3 5]
[1 3 5 7 9]


In [16]:
#Slicing 2-D Arrays
arrslice2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arrslice2D)
print("from second element slice index 1 to 4 =",arrslice2D[1, 1:4])
print("from both element return index 2 = ",arrslice2D[0:2, 3])
print(arrslice2D[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
from second element slice index 1 to 4 = [7 8 9]
from both element return index 2 =  [4 9]
[[2 3 4]
 [7 8 9]]


###Data Types in NumPy

In [17]:
# by default python have these datatypes
# strings - ABCD
# integer - -1,-5,1,2
#float -1.2,1.78,1.5
#boolean - True and False
#complex - complex number 1+2i, 1.5+5j
# i - integer(int)
# b - boolean(bool)
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

####Checking the datatype
  

In [18]:
checktype = np.array([1,2,3,4,5,6])
print(checktype.dtype)
arraytype=np.array(["ram","shyam","geeta"])
print(arraytype.dtype)
defineself = np.array(["ram","shyam","geeta"], dtype='S')
print(defineself.dtype)
# For i, u, f, S and U we can define size as well.
arr = np.array([1,2,3,4,5], dtype='i4')
print(arr)
print(arr.dtype)
# if numpy can not be convert value then it is raised value error

int64
<U5
|S5
[1 2 3 4 5]
int32


In [19]:
#Change data type from integer to boolean:
arr = np.array([1,2,3,40,0,1])
print(arr.dtype)
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

int64
[ True  True  True  True False  True]
bool


###Difference between Copy and View

In [20]:
# an array is that the copy is a new array, and the view is just a view of the original array.
arr = np.array([1,2,3,4,5,6])
x=arr.copy()
arr[0]=12
print(x)
print(arr)

[1 2 3 4 5 6]
[12  2  3  4  5  6]


In [21]:
#this is view
arr = np.array([1,2,3,4,5,6])
x=arr.view()
arr[0]=10
print(x)
print(arr)
# copies owns the data, and views does not own the data

[10  2  3  4  5  6]
[10  2  3  4  5  6]


In [22]:
# base attribute to check if an array owns it's data or not:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


###NumPy Array Shape

In [23]:
import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=24IBG5ISFXP4W7N3'
r = requests.get(url)
data = r.json()
# api key is 24IBG5ISFXP4W7N3
print(data)

{'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume', '2. Symbol': 'IBM', '3. Last Refreshed': '2023-10-27 19:35:00', '4. Interval': '5min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'}, 'Time Series (5min)': {'2023-10-27 19:35:00': {'1. open': '142.3000', '2. high': '142.3000', '3. low': '142.3000', '4. close': '142.3000', '5. volume': '12'}, '2023-10-27 19:10:00': {'1. open': '142.4100', '2. high': '142.4100', '3. low': '142.4100', '4. close': '142.4100', '5. volume': '10'}, '2023-10-27 19:05:00': {'1. open': '142.5400', '2. high': '142.6900', '3. low': '142.5400', '4. close': '142.6900', '5. volume': '201'}, '2023-10-27 19:00:00': {'1. open': '142.5200', '2. high': '142.5500', '3. low': '142.3800', '4. close': '142.3800', '5. volume': '553834'}, '2023-10-27 18:55:00': {'1. open': '142.4800', '2. high': '142.4800', '3. low': '142.4800', '4. close': '142.4800', '5. volume': '1'}, '2023-10-27 18:50:00': {'1. open': '142.5500', '2. hi

In [24]:
#here we are get the shape of an array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
# here first is 2= dimension and second 4= element

#we can use ndim and create multi dimensional array

arr=np.array([1,2,3,4], ndmin=5)
print(arr)
print("shape of array is =", arr.shape)

# here 1= display element
# 4=dimension

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array is = (1, 1, 1, 1, 4)


###NumPy array reshape

In [25]:
# we can chnanges array number of elements and each dimension
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
newarr = arr.reshape(4,3)
print(newarr)
print(newarr.dtype)
print(newarr.ndim)
# here i am convert 1d to 2d

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
int64
2


In [26]:
# we are convert 1-D to 3 -D
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
newarr = arr.reshape(2,3,2) # 2 arrays that contains 3 arrays, each with 2 elements
print(newarr)
print(newarr.dtype)
print(newarr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
int64
3


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4)

print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [28]:
#Returns Copy or View
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [29]:
#Unknown Dimension
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###NumPy Array Iterating

In [30]:
# Here we are Iterating 1-D array
arr=np.array([1,2,3])
for a in arr:
  print(x)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [31]:
# Here we are Iterating 2-D array
arr=np.array([[1,2,3],[4,5,6]])
for a in arr:
  print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [32]:
#If we iterate on a n-D array it will go through n-1th dimension one by one.
arr=np.array([[1,2,3],[4,5,6]])
for a in arr:
  for b in a:
    print(b)

1
2
3
4
5
6


In [33]:
#Iterating 3-D Arrays
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
  print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
#Iterating Arrays Using nditer()
arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [36]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [37]:
#Iterating Array With Different Data Types
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [38]:
#Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)
# it is 2-D array skiping 1 element

1
3
5
7


In [39]:
# Enumerated Iteration Using ndenumerate()
# it is given sequance number
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [40]:
#use in 2- D array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(0, 3, 0) 10
(0, 3, 1) 11
(0, 3, 2) 12


###NumPy Joining Array

In [41]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,9,7,8])
arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 9 7 8]


In [42]:
#Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [43]:
#joining array using stack function
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr=np.stack((arr1, arr2), axis=1)  #if axis is not passd then it is taken 0
print(arr)

#useing hstack() along rows

arr=np.hstack([arr1,arr2]) # it is convert to one rows
print(arr)

arr=np.vstack([arr1,arr2]) # it is convert to one coloumn
print(arr)

arr=np.hstack([arr1,arr2]) # stacking along height
print(arr)

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


###Splitting NumPy Arrays

In [44]:
#Splitting is reverse operation of Joining.
# We use array_split() for splitting arrays

arr = np.array([10,20,30,40,50,421,12,19,13])
newarr = np.array_split(arr, 4)  # yh tukudo m tod dega
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])


[array([10, 20, 30]), array([40, 50]), array([421,  12]), array([19, 13])]
[10 20 30]
[40 50]
[421  12]
[19 13]


In [45]:
#Here we are spliting 2-D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)
newarr1 = np.hsplit(arr, 3)

print(newarr)
print("hsplit array is = ", newarr1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
hsplit array is =  [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


###Searching Arrays

In [47]:
# this is give me index value of 4
arr = np.array([1,2,3,10,20,30,4,50,100])
x=np.where(arr == 4 )
print(x)

(array([6]),)


In [48]:
# this is give me index value of where condition are setisfied
arr = np.array([1,2,3,10,20,30,4,50,100])
x=np.where(arr%2 == 0 )
y=np.where(arr%2 == 1 )
print(x)
print(y)


(array([1, 3, 4, 5, 6, 7, 8]),)
(array([0, 2]),)


In [49]:
# Search Sorted
# this is sort and give me index of given data and index start form 0
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)

print(x)

#Search From the Right Side
y =np.searchsorted(arr, 6, side='right')  #default is left side
print(y)

3
1


In [50]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, [1,2,6,7])
print(x)

[0 0 0 1]


###NumPy Sorting Arrays

In [55]:
#Sorting means putting elements in an ordered sequence.
# Here we can accessing numeric or alphabetical, ascending or descending.

arr = np.array([3,1,0,-2,2])
print(np.sort(arr))

# we can also sort in different datatype
arrstring = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arrstring))
arrbool = np.array([True, False, True])
print(np.sort(arrbool))

[-2  0  1  2  3]
['apple' 'banana' 'cherry']
[False  True  True]


In [59]:
# we can also sort any type of array 2-D array 3-D array and ,ulti dimantional array
arrtwo = np.array([[6,2,5],[8,4,1]])
print(np.sort(arrtwo))

arrtwo = np.array([[6,2,5],[8,4,1]])
print(np.sort(arrtwo))

arrmulti = np.array([4,5,1,2,0,8,-2], ndmin=6)
print(np.sort(arrmulti))
print("Number of dimension : ", arrmulti.ndim)

[[2 5 6]
 [1 4 8]]
[[2 5 6]
 [1 4 8]]
[[[[[[-2  0  1  2  4  5  8]]]]]]
Number of dimension :  6


###NumPy Array Filter


In [60]:
# Here True mean include and false mena exclude
arr = np.array([41,52,45,49])
x= [True, False, True, True]
newarr = arr[x]
print(newarr)

[41 45 49]


In [62]:
# here we are crate empty array emplyment filter

arr =np.array([40,41,52,74,85,45])
filter_arr = []
for a in arr:
  if a>=45:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True, True, True]
[52 74 85 45]


In [63]:
# Here we are fetching the even data only
arr =np.array([10,11,22,15,14,22,47,98,43])
filter_arr = []
for a in arr:
  if a%2==0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[True, False, True, False, True, True, False, True, False]
[10 22 14 22 98]


In [66]:
# Here we are direct filter array
arrfilter = np.array([1,2,3,4,5,6,7,220,10,11,14])
filter_arr = arr>20
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True False False  True  True  True  True]
[22 22 47 98 43]
